### ISSUE TITLE
missing task_slot.h

### ISSUE THREAD

**Issue by janrinze** [Simon-Willcocks/RISC-OS-Kernel-in-C#17]
When building the latest sources it appears that the file task_slot.h is missing.

An easy way to check if files are either checked-in or not is typing 'git status' on the command line.
That will show the files that are changed as well as the files that are not checked in.

**Comment by Simon-Willcocks** [comment]
Sorry, checked in now. I've got a strange error message from OS_SpriteOp, which I'm trying to track down.

I should automatically download the source and run a build when I check things in, shouldn't I?

I've put in some #ifdef instructions to limit the amount of logging: grep for DEBUG__ (two underscores).

The logging on core 0 is duplicated to the UART, so you can see the output in qemu and redirect it if you choose the -nographic option (although you'll probably have to kill it from another terminal).

**Comment by Simon-Willcocks** [comment]
Oh, you can define various things, the DEBUG__ and also SINGLE_CORE, which reduces clutter and makes debugging easier.

./build -DSINGLE_CORE -Wno-unused-const-variable -Wno-unused-function -DDEBUG__SHOW_MODULE_INIT

qemu-system-arm -bios rom.bin -machine raspi2b -d exec,cpu,int,in_asm 2> /tmp/exec.log

(The qemu debug logging slows things down a lot, I also find it helps to pipe it through sed, like 

qemu-system-arm -bios rom.bin -machine raspi2b -d exec,cpu,int,in_asm 2>&1 | sed -n '/Data/,/wfi/p' > /tmp/exec.log 

to see what happens once USR mode is entered, or 0x4600002e in place of Data, to see where OS_SpriteOp (SWI &2e) goes wrong.
